CREATE TABLE CustomerAddress(
    AddressID INT NOT NULL PRIMARY KEY IDENTITY,
    StreetName NVARCHAR(255) NOT NULL,
    StreetNumber NVARCHAR(255) NOT NULL,
    Postcode INT NOT NULL,
    Town NVARCHAR(255) NOT NULL,
    Country NVARCHAR(255)
);

CREATE TABLE Customer(
  CustomerID UNIQUEIDENTIFIER DEFAULT newID() NOT NULL PRIMARY KEY,
  CustomerName NVARCHAR(255) NOT NULL,
  CustomerEmail NVARCHAR(255) NOT NULL,
  CustomerPhoneNumber NVARCHAR(20),
  AddressID INT NOT NULL FOREIGN KEY REFERENCES CustomerAddress(AddressID)
);

CREATE TABLE SystemUser(
  UserID UNIQUEIDENTIFIER DEFAULT newID() NOT NULL PRIMARY KEY,
  FullName NVARCHAR(255) NOT NULL,
  Username NVARCHAR(255) NOT NULL,
  UserPassword NVARCHAR(50) NOT NULL,
  UserRole NVARCHAR(50) NOT NULL
);

CREATE TABLE Document(
  DocumentID UNIQUEIDENTIFIER DEFAULT newID() NOT NULL PRIMARY KEY,
  JobDescription NVARCHAR NOT NULL,
  Notes NVARCHAR,
  CustomerID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Customer(CustomerID)
);

CREATE TABLE User_Document_Link(
  UserID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES SystemUser(UserID),
  DocumentID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Document(DocumentID)
);

CREATE TABLE Document_Image_Link(
  DocumentID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Document(DocumentID),
  ImageBytes VARBINARY NOT NULL  
);